# -*- coding: utf-8 -*-
"""[07]Clustering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EJ1_xn0ZiGkXTAOwiTAxFA5go9A7ViSF
"""

from google.colab import files
uploaded = files.upload()
!pip install mglearn
import mglearn
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

#1. 데이터 생성과 클러스터링 시각화
x,y = make_blobs(random_state = 1) #각각 x = Featuer y = label

kmeans = KMeans(n_clusters = 3)
kmeans.fit(x)

#1.1 클러스터링 결과 시각과
mglearn.discrete_scatter(x[:,0],x[:,1],kmeans.labels_, markers='o')
mglearn.discrete_scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],[0,1,2],markers='^',markeredgewidth=2)

#2. K에 따른 클러스터링 결과
from google.colab import files
uploaded = files.upload()
!pip install mglearn
import mglearn
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

#1. 데이터 생성과 클러스터링 시각화
x,y = make_blobs(random_state = 1) #각각 x = Featuer y = label

#kmeans = KMeans(n_clusters = 3) #클러스터 3개
#kmeans.fit(x)

#1.1 클러스터링 결과 시각과
#mglearn.discrete_scatter(x[:,0],x[:,1],kmeans.labels_, markers='o')
#mglearn.discrete_scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],[0,1,2],markers='^',markeredgewidth=2)

fig,axes = plt.subplots(1,2,figsize=(10,5))

#KMeans에서 클러스터링 2개 설정
kmeans = KMeans(n_clusters=2)
kmeans.fit(x)
assignments = kmeans.labels_
mglearn.discrete_scatter(x[:,0],x[:,1],assignments, ax = axes[0])

#KMeans에서 클러스터링 5개 설정
kmeans = KMeans(n_clusters=5)
kmeans.fit(x)
assignments = kmeans.labels_
mglearn.discrete_scatter(x[:,0],x[:,1],assignments, ax = axes[1])

#2. K에 따른 클러스터링 결과
from google.colab import files
uploaded = files.upload()
!pip install mglearn
import mglearn
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

#1. 데이터 생성과 클러스터링 시각화
#x,y = make_blobs(random_state = 1) #각각 x = Featuer y = label

#kmeans = KMeans(n_clusters = 3) #클러스터 3개
#kmeans.fit(x)

#1.1 클러스터링 결과 시각과
#mglearn.discrete_scatter(x[:,0],x[:,1],kmeans.labels_, markers='o')
#mglearn.discrete_scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],[0,1,2],markers='^',markeredgewidth=2)

#fig,axes = plt.subplots(1,2,figsize=(10,5))

#KMeans에서 클러스터링 2개 설정
#kmeans = KMeans(n_clusters=2)
#kmeans.fit(x)
#assignments = kmeans.labels_
#mglearn.discrete_scatter(x[:,0],x[:,1],assignments, ax = axes[0])

#KMeans에서 클러스터링 5개 설정
#kmeans = KMeans(n_clusters=5)
#kmeans.fit(x)
#assignments = kmeans.labels_
#mglearn.discrete_scatter(x[:,0],x[:,1],assignments, ax = axes[1])

#non - spherical 형태의 cluster 생성후 kmeans 에 적용
from sklearn.datasets import make_moons
x,y = make_moons(n_samples = 200, noise = 0.05, random_state = 0)

kmeans = KMeans(n_clusters=2)
kmeans.fit(x)
y_pred = kmeans.predict(x)

plt.scatter(x[:,0], x[:,1],c = y_pred, cmap = mglearn.cm2, s=60, edgecolors = 'k')
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1], marker='^', c=[mglearn.cm2(0),mglearn.cm2(1)],s=100, linewidth=2, edgecolors='k')
plt.xlabel("feature0")
plt.ylabel("feature1")

#B. wine 성분에 따른 품종 클러스터링
import numpy as np
import pandas as pd
from google.colab import files
uploaded = files.upload()
!pip install mglearn
import mglearn

wine = pd.read_csv('wine.csv')
wine2 = wine[["Class","Alcohol","Malic acid"]] #두개의 Feature 선택
x = np.c_[wine2['Alcohol'],wine2['Malic acid']]
y = wine2['Class']
m = len(wine2)

x = (np.array(x)).reshape(m,2)
y = (np.array(y)).reshape(m,1)

def featureNormalize(x):
  #각 Feature에 대한 평균, 표준편차
  mu = np.mean(x, axis = 0)
  std = np.std(x,axis = 0)

  x_norm = (x - mu)/std

  return x_norm, mu, std

x,mu,std = featureNormalize(x)

#4. 클러스터링 수행
kmeans = KMeans(n_clusters=3)
kmeans.fit(x)

mglearn.discrete_scatter(x[:,0],x[:,1],kmeans.labels_)
plt.legend(["cluster 0","cluster 1", "cluster 2"] , loc = 'best')
plt.xlabel(wine2.columns[1])
plt.ylabel(wine2.columns[2])

#5. 정답 레이블과 비교
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y.reshape(-1), kmeans.labels_+1)
plt.matshow(conf_mat, cmap = plt.cm.gray)
plt.show()

!pip install mglearn
import mglearn
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
#덴드로그램 함수, ward = 거리, 클러스터링 함수 임포트
from scipy.cluster.hierarchy import dendrogram, ward

x,y = make_blobs(random_state = 0, n_samples = 12)
#데이터 배열 x에 ward함수 적용
#scipy의 ward 함수는 병합 클러스터링을 수행할 때 생성
#거리 정보가 담긴 배열을 리턴

linkage_arr = ward(x)
#클러스터 간의 거리 정보가 담신 linkage_arr를 사용해서 덴드로 그램 그리기

dendrogram(linkage_arr)

#클러스터 개수 커트라인 표시
ax = plt.gca()
bounds = ax.get_xbound()
ax.plot(bounds, [7.25, 7.25],'--', c='k')
ax.plot(bounds, [4,4], '--', c='k')

ax.text(bounds[1],7.25, 'two clusters', va = 'center', fontdict = {'size':15})
ax.text(bounds[1],4, 'three clusters', va='center', fontdict = {'size':15})

plt.xlabel("no. of sample")
plt.ylabel("distance between clusters")

#DBSCAN Algorithm
!pip install mglearn
import mglearn
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons
from sklearn.preprocessing import StandardScaler
x,y = make_moons(n_samples = 200, noise = 0.05, random_state = 0)

#평균 0, 분산 1이 되도록 데이터의 스케일 조정
scaler = StandardScaler()
scaler.fit(x)
x = scaler.transform(x)


#Non - spherical한 데이터에 대해서 K-means, Agglomerative, DBSCAN 알고리즘 비교
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics.cluster import adjusted_rand_score
from sklearn.metrics.cluster import silhouette_score
import numpy as np

#클러스터링 알고리즘 리스트화
cluster_algos = [KMeans(n_clusters=2),AgglomerativeClustering(n_clusters=2),DBSCAN()]

#무작위로 클러스터링 알고리즘 할당
random_state = np.random.RandomState(seed = 0)
random_clusters = random_state.randint(low = 0, high = 2, size = len(x))


fig, axes = plt.subplots(1,4,figsize=(15,3),subplot_kw={'xticks':(), 'yticks':()})

axes[0].scatter(x[:,0],x[:,1],c=random_clusters, cmap=mglearn.cm3, s=60, edgecolors='black')
axes[0].set_title("random assignment-silhouette:{:.2f}".format(adjusted_rand_score(y, random_clusters)))

#세 가지 알고리즘으로 할당한 클러스터 시각화
for ax,algo in zip(axes[1:],cluster_algos):
  clusters = algo.fit_predict(x)
  ax.scatter(x[:,0],x[:,1], c = clusters, cmap = mglearn.cm3, s = 60, edgecolors = 'black')
  ax.set_title("{}-silhouette:{:.2f}".format(algo.__class__.__name__, silhouette_score(x, clusters)))

#Non - spherical한 데이터에 대해서 K-means, Agglomerative, DBSCAN 알고리즘 비교