# -*- coding: utf-8 -*-
"""[실습03]다항 선형 회귀

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RdBwSD_W-iyczNemPgRkOw7qQ_s0Vyej
"""

from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd
#1. 데이터 불러오기
data = pd.read_csv('house_price_us.txt', names=['size','n_room','price'])

x = np.c_[data['size'],data['n_room']]
y = data['price']
m = len(data)

x = (np.array(x)).reshape(m,2)
y = (np.array(y)).reshape(m,1)
print(x.shape, y.shape)

#2. 그래프 그리기
import matplotlib.pyplot as plt
plt.plot(x[:,0].reshpae(-1),y,'b.')
plt.xlabel("size of house in square")
plt.ylabel("price in KRW")
plt.show()

plt.plot(x[:,1].reshpae(-1),y,'b.')
plt.xlabel("# of rooms")
plt.ylabel("Price in KRW")
plt.show()

#3. Feature Scailing
def featureNormalize(x):
  mu = np.mean(x,axis=0)
  std = np.std(x,axis=0)
  x_norm = (x-mu)/std
  return x_norm, mu, std

#4. Gradient Descent -> theta
x_b = np.c_[np.ones((m,1)),x]

learning_rate = 0.01 # 알파 값
n_iter = 400 #반복횟수

theta = np.random.randn(3,1)#세타 값에 대한 무작위 초기화
gradients = np.zeros((3,1))

for i in range(n_iter):
  gradients = 2.0/m+x_b.T.dot(x_b.dat(theta)-y)
  theta = theta-learning_rate*gradients

#5. 임의의 집 크기 (x_my)에 대한 집 값 예측하기
x_mine = np.array([890,2])
x_mine = (x_mine-mu)/std #feature normalization

x_mine_b = np.c_[np.ones((1,1)),x_mine]
y_predict = x_mine_b.dot(theta)

print(y_predict+"달러")

