# -*- coding: utf-8 -*-
"""[실습04, 05]로지스틱 회귀와 정규화

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RvMOdb3No1EcuEHHjJ85OrmJMHxCr04a
"""

#1. 합격여부 데이터 읽기
from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd
data = pd.read_csv('admit.txt', names=['ex1','ex2', 'Admitted'])
print(data)

x = np.c_[data['ex1'],data['ex2']]
y = data['Admitted']

#2. 그래프 그리기
from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv('admit.txt', names=['ex1','ex2', 'Admitted'])
print(data)

x = np.c_[data['ex1'],data['ex2']]
y = data['Admitted']
pos = [] #합격
neg = [] #불합격

for(i,val) in enumerate(y):
  if val== 1:
    pos.append(i)
  else:
    neg.append(i)
plt.plot(x[pos,0].reshape(-1),x[pos,1].reshape(-1),'b+', label = 'Admitted') #x[pos,0] x배열에서 0번쨰 데이터를 그림, x[pos,1]배열에서 1번째 데이터를 그림
plt.plot(x[neg,0].reshape(-1), x[neg,1].reshape(-1), 'ro',label = 'Not Admitted')
plt.xlabel("Exam 1 score")
plt.ylabel("Exam 2 score")
plt.legend(loc = 'upper right')
plt.show()

#3. 학습

from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(solver='liblinear', C=10) #C = 람다의 역수, 클수록 규제 약화
log_reg.fit(x,y)
log_reg.predict([[30,70],[50,90]]) #exam 1 30점 exam 2 70점 합격 불합격? / exam1 50점 exam2 90점 합격 불합격?

