# -*- coding: utf-8 -*-
"""[ML][실습02]선형 회귀

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1g71P0pi01TLNi_Q7jOl4cuZBxTYwGJ
"""

from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#1. 데이터 불러오기
data = pd.read_csv('house_price.txt', names=['size','price'])
print(data)


x = data['size'] #데이터 array에서 집 평수
y = data['price'] #데이터 array에서 집 면적에 대한 금액
m = len(data) #전체 데이터 길이

X = (np.array(x).reshape(m,1)) #집 평수에 대한 array 52 * 1 vector
Y = (np.array(y).reshape(m,1)) #집 평수에 대한 금액 array 52 *1 vector
print(X.shape, Y.shape)

#2. 불러온 데이터를 기반으로 pyplot을 이용하여 그래프 표현
plt.plot(X,Y, 'b.')
plt.xlabel("Size of house in Square feet")
plt.ylabel("Price in KRW")
plt.show()

#3. Gradient descent(경사 하강 알고리즘) -> theta
X_b = np.c_[np.ones((m,1)),X] #두개의 행렬을 이어 붙인것 np.ones(m,1) 1로 이루어진 행렬 * X행렬을 concetanate

learning_rate = 0.001 #학습 률
n_iter = 200 #전체 업데이트 횟수
theta = np.zeros((2,1)) #2 x 1 행렬 0으로 초기화
gradients = np.zeros((2,1)) #gradient도 2 x 1 행렬 0으로 초기

for i in range(n_iter):
  theta = theta - learning_rate*gradients

#4. 집 크기 최소 ~ 최대 * theta 그래프 그리기
x_new = np.array([[10],[90]])
x_new_b = np.c_[np.ones((2,1)),x_new]
y_predict = x_new_b.dot(theta)
print(y_predict)

plt.plot(x_new,y_predict, 'r-')
plt.plot(X,Y,'b.')
plt.xlabel("Size of house in Square feet")
plt.ylabel("Price in KRW")
plt.show()
