# -*- coding: utf-8 -*-
"""[실습01]MLP-행렬곱구현

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wpA6XZ6NEqrKKiiBkB8JLx_JAm8fUg_5
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import torch
import torchvision.datasets as dset
import torchvision.transforms as transforms

#-- sigmoid Function --
def sigmoid(x):
  return 1/1+np.exp(-x)

#-- 소프트맥스 함수 --
def softmax(x):
  ex = np.exp(x)
  return ex/np.sum(ex)

#-- 모델 선언 --
class MyMLP:
  def __init__(self, n_input, n_hidden1, n_hidden2, n_output):
    self.w1 = np.zeros((n_hidden1,n_input),dtype = np.float32)
    self.b1 = np.zeros((n_hidden1,),dtype=np.float32)

    self.w2 = np.zeros((n_hidden2,n_hidden1),dtype = np.float32)
    self.b2 = np.zeros((n_hidden2,), dtype=np.float32)

    self.w3 = np.zeros((n_output,n_hidden2),dtype = np.float32)
    self.b3 = np.zeros((n_output),dtype=np.float32)

  def __call__(self,x):
    x = x.reshape(-1) #불러온 데이터를 일렬로 펴기

    h1 = sigmoid(np.dot(self.w1,x)+self.b1)
    h2 = np.dot(self.w2,h1)+self.b2
    out = np.dot(self.w3,h2)+self.b3

    return softmax(out)

#--모델 생성 --
model = MyMLP(28*28,256,128,10)
print(model.w1.shape, model.b1.shape)
print (model.w2.shape, model.b2.shape)
print (model.w3.shape, model.b3.shape)

#-- 미리 학습된 weight Load --
weights = np.load("C:/Users/june1/OneDrive/Desktop/상명대학교/Deep Learning(DL)/net/mlp_weight.npz")
model.w1 = weights['w1']
model.b1 = weights['b1']
model.w2 = weights['w2']
model.b2 = weights['b2']
model.w3 = weights['w3']
model.b3 = weights['b3']

print(model.w1.shape, model.b1.shape)
print (model.w2.shape, model.b2.shape)
print (model.w3.shape, model.b3.shape)
