# -*- coding: utf-8 -*-
"""[실습06]Support Vector Machine(SVM)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rcDdw0PdgAPmpx4glc2yHS9SHYIiNET9
"""

#1. Gaussian Kernel 그리기
import numpy as np
import matplotlib.pyplot as plt

def GaussianKernel(v1,v2,sigma):
  res = np.exp(-np.linalg.norm(v1-v2)**2//2*sigma**2)
  return res

#1.1 x1, x2, z 값 구하기
d = 100 #split
x1 = np.linspace(0,1,d) #x1축
x2 = np.linspace(0,10,d) #x2 축
l1 = [3,5]
z = np.zeros((d,d))
sigma = 1.5
for i,t1 in enumerate(x1):
  for j, t2 in enumerate(x2):
    val = GaussianKernel(np.array([t1,t2]),l1,sigma)
    z[i,j] = val

#2. 그리기
from mpl_toolkits import mplot3d
px,py = np.meshgrid(x1,x2)
fig = plt.figure()
ax = plt.axes(projection = '3d')
ax.contour3D(px,py,z,100,cmap='jet')
ax.set_xlabel('x1')
ax.set_ylabel('x2')
ax.set_zlabel('Z');
plt.show()

fig

#2. 선형 SVM 분류
from google.colab import files
uploaded = files.upload()
import numpy as np
from scipy.io import loadmat
data = loadmat('data1.mat')
x = data['X'] #xlabel 데이터
y = data['y'] #ylabel 데이터
m = len(y)

#2.2 선형 SVM 분류 :: 그래프 그리기
import matplotlib.pyplot as plt
pos = []
neg = []

#참 거짓 분류
for i,val in enumerate(y):
  if val == 1:
    pos.append(i)
  else:
    neg.append(i)

plt.plot(x[pos,0].reshape(-1), x[pos,1].reshape(-1), 'b+', label = 'y=1')
plt.plot(x[neg,0].reshape(-1),x[neg,1].reshape(-1),'ro', label = 'y=0')
plt.xlabel('x1')
plt.ylabel('x2')
plt.legend(loc = 'upper right')
plt.title("Data 1")
plt.show()

#3. 학습
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

svm_clf = Pipeline([
    ("scaler",StandardScaler()),
    ("linear_svc",LinearSVC(C=1, loss = "hinge"))
])

svm_clf.fit(x,y) #모델 학습

svm_clf.predict([[2.3,2.7],[3.7,3.9]]) #x1, x2, x1**2, x2**2

#4. Decision Boundary

x_min, x_max = x[:,0].min()-0.2, x[:,0].max()+0.2
y_min, y_max = x[:,1].min()-0.2, x[:,1].max()+0.2
h = .02
xx, yy = np.meshgrid(np.arange(x_min, x_max,h), np.arange(y_min,y_max,h))
z = svm_clf.predict(np.c_[xx.ravel(),yy.ravel()])

#색상 넣는 코드
z = z.reshape(xx.shape)
plt.figure(1)
plt.pcolormesh(xx,yy,z,cmap = plt.cm.Paired)

plt.plot(x[pos,0].reshape(-1),x[pos,1].reshape(-1),'b+',label = 'y=1')
plt.plot(x[neg,0].reshape(-1),x[neg,1].reshape(-1),'ro',label='y=0')
plt.xlabel('x1')
plt.ylabel('x2')
plt.legend(loc = 'upper right')

plt.xlim(xx.min(),xx.max())
plt.ylim(yy.min(),yy.max())
plt.xticks(())
plt.yticks(())
plt.show()

#3. 비선형 SVM 분류
from google.colab import files
uploaded = files.upload()
import numpy as np
from scipy.io import loadmat
data = loadmat('data2.mat')

x = data['X']
y = data['y']
m = len(y)

#3.2 그래프 그리기
pos = []
neg = []

for i,val in enumerate(y):
  if val == 1:
    pos.append(i)
  else:
    neg.append(i)

import matplotlib.pyplot as plt
plt.plot(x[pos,0].reshape(-1), x[pos,1].reshape(-1), 'b+', label = 'y=1')
plt.plot(x[neg,0].reshape(-1), x[neg,1].reshape(-1),'ro',label ='y=0')
plt.xlabel('x1')
plt.ylabel('x2')
plt.legend('upper right')
plt.title("Data 2")
plt.show()

#3.3 학습
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

svm_clf = Pipeline([
    ("scaler",StandardScaler()),
    ("linear_svc",SVC(kernel = "rbf", gamma=10, C=1)) # C = 람다 역수 즉 c가 작으면 규제 강화

])

svm_clf.fit(x,y) #모델 학습

svm_clf.predict([[2.3,2.7],[3.7,3.9]]) #x1, x2, x1**2, x2**2

#4. Decision Boundary
x_min, x_max = x[:,0].min()-0.2, x[:,0].max()+0.2
y_min, y_max = x[:,1].min()-0.2, x[:,1].max()+0.2
h = .02
xx, yy = np.meshgrid(np.arange(x_min, x_max,h), np.arange(y_min,y_max,h))
z = svm_clf.predict(np.c_[xx.ravel(),yy.ravel()])

#색상 넣는 코드
z = z.reshape(xx.shape)
plt.figure(1)
plt.pcolormesh(xx,yy,z,cmap = plt.cm.Paired)

plt.plot(x[pos,0].reshape(-1),x[pos,1].reshape(-1),'b+',label = 'y=1')
plt.plot(x[neg,0].reshape(-1),x[neg,1].reshape(-1),'ro',label='y=0')
plt.xlabel('x1')
plt.ylabel('x2')
plt.legend(loc = 'upper right')

plt.xlim(xx.min(),xx.max())
plt.ylim(yy.min(),yy.max())
plt.xticks(())
plt.yticks(())
plt.show()
