# -*- coding: utf-8 -*-
"""[실습04,05]로지스틱회귀와 정규:반도체 불량품 여부 판단

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJeHwF_PiOYRizmKsClk0G6ZhQ1P6c-l
"""

#불량여부 데이터 읽기
from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd
data = pd.read_csv('qa.txt', names=['t1','t2','Passed'])# t1 = test1에 대한 수치값 t2 = test2에 대한 수치값
print(data)
x = np.c_[data['t1'], data['t2']]
y = data['Passed']

#2. 그래프 그리기
from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd
data = pd.read_csv('qa.txt', names=['t1','t2','Passed'])# t1 = test1에 대한 수치값 t2 = test2에 대한 수치값
print(data)
x = np.c_[data['t1'], data['t2']]
y = data['Passed']

import matplotlib.pyplot as plt
pos = []
neg = []

for(i,val) in enumerate(y):
  if val == 1:
    pos.append(i)
  else:
    neg.append(i)

plt.plot(x[pos,0].reshape(-1), x[pos,1].reshape(-1), 'b+', label = 'Passed')
plt.plot(x[neg,0].reshape(-1), x[neg,1].reshape(-1), 'ro', label = 'Failed')
plt.xlabel("Microchip test 1")
plt.ylabel("Microchip test 2")
plt.legend('loc = upper right')
plt.show()

#3. 학습
from sklearn.preprocessing import PolynomialFeatures #sklearn에서 다항함수 사용
from sklearn.linear_model import LogisticRegression
degree = 2 #차수가 2개
poly_features = PolynomialFeatures(degree = degree, include_bias = False)
x_poly = poly_features.fit_transform(x) # 각각 제곱한 값이 들어간다

log_reg = LogisticRegression(penalty = '12', solver='liblinear', C=1e-1) #규제 강화
log_reg.fit(x_poly,y)



#5. 로지스틱 회귀 성능 측정
from google.colab import files
#uploaded = files.upload()
import numpy as np
import pandas as pd
data = pd.read_csv('qa.txt', names=['t1','t2','Passed'])# t1 = test1에 대한 수치값 t2 = test2에 대한 수치값
print(data)
x = np.c_[data['t1'], data['t2']]
y = data['Passed']

import matplotlib.pyplot as plt
pos = []
neg = []

for(i,val) in enumerate(y):
  if val == 1:
    pos.append(i)
  else:
    neg.append(i)

plt.plot(x[pos,0].reshape(-1), x[pos,1].reshape(-1), 'b+', label = 'Passed')
plt.plot(x[neg,0].reshape(-1), x[neg,1].reshape(-1), 'ro', label = 'Failed')
plt.xlabel("Microchip test 1")
plt.ylabel("Microchip test 2")
plt.legend('loc = upper right')
plt.show()
from sklearn.preprocessing import PolynomialFeatures #sklearn에서 다항함수 사용
from sklearn.linear_model import LogisticRegression
degree = 2 #차수가 2개
poly_features = PolynomialFeatures(degree = degree, include_bias = False)
x_poly = poly_features.fit_transform(x) # 각각 제곱한 값이 들어간다

log_reg = LogisticRegression(penalty = 'l2', solver='liblinear', C=1e-1) #규제 강화
log_reg.fit(x_poly,y)
y_pred = log_reg.predict(x_poly)

#5.2 confution matrix
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y,y_pred)
plt.matshow(conf_mat, cmap = plt.cm.gray)
plt.show()

#5.3 precision & recall
from sklearn.metrics import precision_score, recall_score
print("precision_score:", precision_score(y,y_pred))
print("recall_score:", recall_score(y,y_pred))

y_scores = log_reg.decision_function(x_poly)
#ROC curve
from sklearn.metrics import roc_curve
fpr, tpr, thresholds = roc_curve(y,y_scores)

def plot_roc_curve(fpr, tpr, label = None):
  plt.plot(fpr, tpr, linewidth = 2, label = label)
  plt.plot([0,1],[0,1], 'k--')
  plt.axis([0,1,0,1])
  plt.xlabel('FPR')
  plt.ylabel('TPR')
plot_roc_curve(fpr, tpr)
plt.show()
