# -*- coding: utf-8 -*-
"""[실습]붓꽃의 품종분류

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWOZQuN0bqeEVrm5_NXhk29YBIpkmFjH
"""

#Machin Learning Cycle
import numpy as np
import pandas as pd

#1. 데이터 적재
from sklearn.datasets import load_iris #붓꽃 데이터 세트
from sklearn.model_selection import train_test_split #데이터 훈련 세트(label)을 무작위로 섞는 라이브러리
iris_dataset = load_iris()

#전체 iris에 대한 출력
print("iris_dataset size:\n", iris_dataset.keys()) #라이브러리 iris_dataset에 들어 있는 키값들
print(iris_dataset["DESCR"][:193]+"\n...") #라이브러리에 들어있는 전체 데이터 셋
print("name of target:",iris_dataset['target_names']) #데이터 꽃 이름들
print("name of feature:",iris_dataset['feature_names']) #데이터 특징
print("type of data:",type(iris_dataset['data'])) #데이터 타입 형식
print("sizeof data:",iris_dataset['data'].shape) #전체 데이터 크기
print("first five rows of data\n",iris_dataset['data'][:5]) #첫 5줄 데이터 출력
print("type of target",type(iris_dataset['target'])) #target에 대한 데이터 타입
print("size of target",iris_dataset['target'].shape)


#2. Evaluation for performance: Train data& test data
x_train, x_test, y_train, y_test = train_test_split(iris_dataset['data'],iris_dataset['target'],random_state = 0) #전체 데이터 셋 적절하게 test data, train data로 분리
print("size of x_train:",x_train.shape) # #of data * 75% #of feature
print("size of y_train:",y_train.shape) #x_train에 대한 정답 레이블 (#of data*75%)
print("size of x_test:",x_test.shape)
print("size of y_test:",y_test.shape)

#3.Look Around iris data with scatter plot Graph

iris_dataframe = pd.DataFrame(x_train, columns=iris_dataset.feature_names)
pd.plotting.scatter_matrix(iris_dataframe, c=y_train, figsize=(15,15), marker='o', hist_kwds={'bins':20}, s=60, alpha=.8 )

#4. Model Loading (K-NN Algorithm)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

#Model Training (모델 학습 담당 코드)
knn.fit(x_train, y_train) # x_train = 훈련용 데이터 셋 y_train = 훈련용 데이터 셋

#5. Prediction (예측)
x_new = np.array([[5,2.9,1,0.2]]) #1x4 Matrix
prediction = knn.predict(x_new) #새로 넣은 임의의 데이터에 대한 예측
print("prediction:",prediction)
print("predicted target name:", iris_dataset['target_names'][prediction]) #예측한 변수 값 prediction을 iris_dataset에 넣어서 해당 데이터에 대한 값 측정

#6. Performance
y_pred = knn.predict(x_test) #훈련용 데이터가 아닌 테스트 데이터를 넣어 예측
print("predicted test dataset:\n",y_pred) #예측한 데이터 출력
print("Accuracy for test set:{.2f}".format(np.mean(y_pred = y_test))) # 예측한 데이터 y_pred와 정답 레이블 y_test가 맞을 경우의 모델 정확도 측

